security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\Restaurante:
            algorithm: 'plaintext'
            ignore_case: false

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Restaurante
                property: correo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: categorias
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
